version: '3.5'

services:
  # api01: &api
  #   build: .
  #   hostname: api01
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DB_USER=admin
  #     - DB_PASS=123
  #     - DB_DATABASE=rinha
  #     - PORT=8080
  #   depends_on:
  #     - db
  #   ports:
  #     - '8081:8080'
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.45'
  #         memory: '200MB'

  # api02:
  #   <<: *api
  #   hostname: api02
  #   ports:
  #     - '8082:8080'

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - api01
  #     - api02
  #   ports:
  #     - '9999:9999'
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.15'
  #         memory: '10MB'

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '140MB'
networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
